**Работу выполнила:**
Нгуен Кхань Нгок - 345148

# **Распознавание активности человека на основе данных с мобильных сенсоров**

Необходимо по данным с мобильных сенсоров при помощи прикладных алгоритмов машинного обучения предсказать активность человека по шести классам движений:
Движется по прямой

Движется вверх (например, движение по лестнице вверх)

Движется вниз (например, движение по лестнице вниз)

Сидит

Стоит

Лежит

### **Сведения о наборе данных**
Набор данных содержит записи датчиков со сматфонов (акселерометр и гироскоп с частотой дискретизации 50 Гц) от 30 участников, выполняющих следующие действия: ходьба, ходьба по лестнице, ходьба по лестнице, сидение, стояние и лежание. Данные были предварительно обработаны при помощи фильтров шума. Набор данных представлен Хорхе Л. Рейес-Ортисом.


Признаки были извлечены из 3-х осевых необработанных сигналов акселерометра и гироскопа tAcc-XYZ и tGyro-XYZ. Эти сигналы были сняты с постоянной частотой 50 Гц. Затем были отфильтрованны с помощью медианного фильтра и низкочастотного фильтра Баттерворта 3-го порядка с частотой 20 Гц для удаления шумов. Аналогичным образом сигнал ускорения был разделен на сигналы ускорения тела и гравитации (tBodyAcc-XYZ и tGravityAcc-XYZ) с помощью другого низкочастотного фильтра Баттерворта с угловой частотой 0,3 Гц. Линейное ускорение тела и угловая скорость были использованы для получения сигналов "рывка" — (tBodyAccJerk-XYZ и tBodyGyroJerk-XYZ). Также величина этих трехмерных сигналов была расчитана с использованием евклидовой нормы — (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).


Наконец, к некоторым из этих сигналов было применено быстрое преобразование Фурье (БПФ), в результате чего получились fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Обратите внимание на "f" для обозначения сигналов в частотной области).

Набор переменных, которые были оценены по этим сигналам, следующий:

mean(): Среднее значение

std(): Стандартное отклонение

mad(): Среднее абсолютное отклонение

max(): Наибольшее значение в массиве

min(): Наименьшее значение в массиве

sma(): Область величины сигнала

energy(): Мера энергии. Сумма квадратов, деленная на количество значений.

iqr(): Интерквартильный размах

entropy(): Энтропия сигнала

arCoeff(): Коэффициенты авторегрессии с порядком Burg, равным 4

correlation(): коэффициент корреляции между двумя сигналами

maxInds(): индекс частотной составляющей с наибольшей величиной

meanFreq(): средневзвешенное значение частотных компонент для получения средней частоты

skewness(): перекос сигнала в частотной области

kurtosis(): эксцесс сигнала в частотной области

bandsEnergy(): Энергия частотного интервала в пределах 64 бинов БПФ каждого окна.

angle(): Угол между векторами.

### **Импорт библиотек**
Первым делом импортируем необходимые библиотеки для работы с данными:

In [13]:
import os
import pandas as pd
import numpy as np

### **Считываем набор данных**

In [15]:
def read_data(dirpath, filename):
    return pd.read_csv(os.path.join(dirpath, filename))

dirpath = '/Users/imnupeww/Documents/AI/LAB1'
df_train = read_data(dirpath, 'train.csv')
df_train.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,...,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627,1,STANDING
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,...,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317,1,STANDING
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,...,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118,1,STANDING
3,0.279174,-0.026201,-0.123283,-0.996091,-0.983403,-0.990675,-0.997099,-0.982750,-0.989302,-0.938692,...,-0.482845,-0.036788,-0.012892,0.640011,-0.485366,-0.848649,0.181935,-0.047663,1,STANDING
4,0.276629,-0.016570,-0.115362,-0.998139,-0.980817,-0.990482,-0.998321,-0.979672,-0.990441,-0.942469,...,-0.699205,0.123320,0.122542,0.693578,-0.615971,-0.847865,0.185151,-0.043892,1,STANDING

In [16]:
df_test = read_data(dirpath, 'test.csv')
df_test.head()

,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,...,fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)",subject,Activity
0,0.257178,-0.023285,-0.014654,-0.938404,-0.920091,-0.667683,-0.952501,-0.925249,-0.674302,-0.894088,...,-0.705974,0.006462,0.162920,-0.825886,0.271151,-0.720009,0.276801,-0.057978,2,STANDING
1,0.286027,-0.013163,-0.119083,-0.975415,-0.967458,-0.944958,-0.986799,-0.968401,-0.945823,-0.894088,...,-0.594944,-0.083495,0.017500,-0.434375,0.920593,-0.698091,0.281343,-0.083898,2,STANDING
2,0.275485,-0.026050,-0.118152,-0.993819,-0.969926,-0.962748,-0.994403,-0.970735,-0.963483,-0.939260,...,-0.640736,-0.034956,0.202302,0.064103,0.145068,-0.702771,0.280083,-0.079346,2,STANDING
3,0.270298,-0.032614,-0.117520,-0.994743,-0.973268,-0.967091,-0.995274,-0.974471,-0.968897,-0.938610,...,-0.736124,-0.017067,0.154438,0.340134,0.296407,-0.698954,0.284114,-0.077108,2,STANDING
4,0.274833,-0.027848,-0.129527,-0.993852,-0.967445,-0.978295,-0.994111,-0.965953,-0.977346,-0.938610,...,-0.846595,-0.002223,-0.040046,0.736715,-0.118545,-0.692245,0.290722,-0.073857,2,STANDING

### **Загрузим полный набор данных и сохранить его под следующими четырьмя переменными**

train_X: признаки, используемые для обучения модели

train_y: метки, используемые для обучения модели

test_X: признаки, используемые для проверки модели

test_y: метки, используемые для проверки модели

In [5]:
def load_dataset(label_dict):
    trainX = read_data(dirpath, 'train.csv').values[:, :-2]
    trainY = read_data(dirpath, 'train.csv')['Activity']
    trainY = trainY.map(label_dict).values

    testX = read_data(dirpath, 'test.csv').values[:, :-2]
    testY = read_data(dirpath, 'test.csv')
    testY = testY['Activity'].map(label_dict).values
    return(trainX, trainY, testX, testY)

label_dict = {"WALKING":0, "WALKING_UPSTAIRS":1, "WALKING_DOWNSTAIRS":2, "SITTING":3, "STANDING":4, "LAYING":5}
trainX, trainY, testX, testY = load_dataset(label_dict)

### **Выбор модели**

Импортируйте выбранную вами модель из библиотеки sklearn и инициализируйте её в объект model:
Также необходимо выбрать несколько моделей ML для сравнения полученных результатов.

**KNN model**

In [6]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=4)

### **Обучение модели**

Обучите модель, используя признаки из обучающего набора (train_X) и метки в качестве базовой истины (train_y).

In [7]:
model.fit(trainX, trainY)

KNeighborsClassifier(n_neighbors=4)

In [8]:
yhat = model.predict(testX)
yhat

array([4, 4, 4, ..., 1, 1, 0])

In [9]:
from sklearn.metrics import classification_report
target_names = ['Walking', 'Walking Upstairs', 'Walking Downstairs', 'Sitting', 'Standing', 'Laying']

print(classification_report(testY, yhat, target_names=target_names))

                    precision    recall  f1-score   support

           Walking       0.83      0.98      0.90       496
  Walking Upstairs       0.88      0.89      0.89       471
Walking Downstairs       0.95      0.74      0.83       420
           Sitting       0.85      0.86      0.85       491
          Standing       0.87      0.86      0.86       532
            Laying       1.00      0.99      1.00       537

          accuracy                           0.89      2947
         macro avg       0.90      0.89      0.89      2947
      weighted avg       0.90      0.89      0.89      2947

**SVM model**

In [30]:
from sklearn.svm import SVC
model_SVC = SVC(C=100)

model_SVC.fit(trainX, trainY)

array([4, 4, 4, ..., 1, 1, 1])

In [31]:
yhat_SVC = model_SVC.predict(testX)
yhat_SVC

array([4, 4, 4, ..., 1, 1, 1])

In [21]:
print(classification_report(testY, yhat_SVC, target_names=target_names))

                    precision    recall  f1-score   support

           Walking       0.96      0.99      0.97       496
  Walking Upstairs       0.95      0.96      0.96       471
Walking Downstairs       0.99      0.95      0.97       420
           Sitting       0.98      0.90      0.94       491
          Standing       0.92      0.98      0.95       532
            Laying       1.00      1.00      1.00       537

          accuracy                           0.97      2947
         macro avg       0.97      0.96      0.96      2947
      weighted avg       0.97      0.97      0.97      2947

**Decision Tree**

In [32]:
from sklearn.tree import DecisionTreeClassifier
model_DTC = DecisionTreeClassifier()

model_DTC.fit(trainX, trainY)

DecisionTreeClassifier()

In [24]:
yhat_DCT = model_DTC.predict(testX)
yhat_DCT

array([4, 4, 4, ..., 1, 0, 1])

In [26]:
print(classification_report(testY, yhat_DCT, target_names=target_names))

                    precision    recall  f1-score   support

           Walking       0.85      0.89      0.87       496
  Walking Upstairs       0.81      0.80      0.81       471
Walking Downstairs       0.88      0.85      0.86       420
           Sitting       0.83      0.76      0.79       491
          Standing       0.79      0.85      0.82       532
            Laying       1.00      1.00      1.00       537

          accuracy                           0.86      2947
         macro avg       0.86      0.86      0.86      2947
      weighted avg       0.86      0.86      0.86      2947